webstore/config/routes.rb
Rails.application.routes.draw do
  resources :clientes
  resources :produtos
  resources :fornecedores
  resources :acs do
    collection do
			get :autocomplete_fornecedor_nome
			get :autocomplete_produto_nome
    end
  end

  resources :compras do
    collection do
      put :gerar_parcelas
		end
  end
	
  root to: "welcome#index"
end

webstore/app/controllers/fornecedores_controller.rb
class FornecedoresController < ApplicationController
  before_action :set_fornecedor, only: %i[ show edit update destroy ]

  # GET /fornecedores or /fornecedores.json
  def index
    @fornecedores = Fornecedor.all
  end

  # GET /fornecedores/1 or /fornecedores/1.json
  def show
  end

  # GET /fornecedores/new
  def new
    @fornecedor = Fornecedor.new
  end

  # GET /fornecedores/1/edit
  def edit
  end

  # POST /fornecedores or /fornecedores.json
  def create
    @fornecedor = Fornecedor.new(fornecedor_params)

    respond_to do |format|
      if @fornecedor.save
        format.html { redirect_to fornecedor_url(@fornecedor), notice: "Fornecedor criado com sucesso." }
        format.json { render :show, status: :created, location: @fornecedor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fornecedores/1 or /fornecedores/1.json
  def update
    respond_to do |format|
      if @fornecedor.update(fornecedor_params)
        format.html { redirect_to fornecedor_url(@fornecedor), notice: "Fornecedor atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @fornecedor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedores/1 or /fornecedores/1.json
  def destroy
    @fornecedor.destroy

    respond_to do |format|
      format.html { redirect_to fornecedores_url, notice: "Fornecedor excluído com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fornecedor
      @fornecedor = Fornecedor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fornecedor_params
      params.require(:fornecedor).permit(:nome, :cpf_cnpj)
    end
end

webstore/app/helpers/fornecedores_helper.rb
module FornecedoresHelper
end

webstore/app/views/fornecedores/_form.html.erb
<%= form_with(model: fornecedor, local: true, :class => 'form-floating') do |form| %>
  <% if fornecedor.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger"><%= pluralize(compra.errors.count, compra.errors.count > 1 ? "erros impediram" : "erro impediu") %> que este fornecedor fosse salvo:
				<ul>
					<% fornecedor.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
				</ul>
			</div>
    </div>
  <% end %>

  <div class="row">
    <div class="col">
      <div class="form-floating mb-3">
  	    <%= form.text_field :nome, {class: "form-control"} %>
        <%= form.label :nome %>
      </div>
	</div>
    <div class="col">
      <div class="form-floating mb-3">
  	    <%= form.text_field :cpf_cnpj, {class: "form-control"} %>
        <%= form.label :cpf_cnpj %>
      </div>
	</div>
    <div class="actions pt-2 mb-2">
			<%= link_to 'Voltar', fornecedores_path, class: "btn btn-secondary text-white" %>
      <%= form.submit(:class => 'btn btn-success') %>
    </div>
  </div>
<% end %>

webstore/app/views/fornecedores/edit.html.erb
<h2>Editando Fornecedor</h2>

<%= render 'form', fornecedor: @fornecedor %>

webstore/app/views/fornecedores/index.html.erb
<h2>Lista de Fornecedores</h2>
<p id="notice"><%= notice %></p>
<table id="datatable" class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>CPF/CPNJ</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @fornecedores.each do |fornecedor| %>
      <tr>
        <td class="align-middle"><%= fornecedor.try(:nome) %></td>
        <td class="align-middle"><%= fornecedor.try(:cpf_cnpj) %></td>
		
        <td>
			<%= link_to 'Exibir', fornecedor, class: "btn btn-info text-white" %>
			<%= link_to 'Editar', edit_fornecedor_path(fornecedor), class: "btn btn-warning text-white" %>
			<%= link_to 'Excluir', fornecedor, class: "btn btn-danger text-white", method: :delete, data: { confirm: 'Tem certeza?' } %>
		</td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Novo Fornecedor', new_fornecedor_path, class: "btn btn-primary text-white" %>

webstore/app/views/fornecedores/new.html.erb
<h2>Novo Fornecedor</h2>

<%= render 'form', fornecedor: @fornecedor %>

webstore/app/views/fornecedores/show.html.erb
<h2>Exibindo Fornecedor</h2>

<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>


<fieldset disabled>
<div class="row">
	<div class="col-md-6">
  	<div class="mb-3">
  	  <label class="form-label">Nome:</label>
  	  <input type="text" class="form-control" value="<%= @fornecedor.nome %>">
  	</div>
	</div>
	<div class="col-md-6">
		<div class="mb-3">
			<label class="form-label">CPF/CNPJ:</label>
			<input type="text" class="form-control" value="<%= @fornecedor.cpf_cnpj %>">
		</div>
	</div>
</div>
</fieldset>
<%= link_to 'Voltar', fornecedores_path, class: "btn btn-secondary text-white" %>
<%= link_to 'Editar', edit_fornecedor_path(@fornecedor), class: "btn btn-warning text-white" %>