webstore/config/routes.rb
Rails.application.routes.draw do
  resources :clientes
  resources :produtos
  resources :fornecedores
  resources :acs do
    collection do
			get :autocomplete_fornecedor_nome
			get :autocomplete_produto_nome
    end
  end

  resources :compras do
    collection do
      put :gerar_parcelas
		end
  end
	
  root to: "welcome#index"
end

webstore/app/models/produto.rb
class Produto < ApplicationRecord
  validates :nome, presence: true
  validates :preco_venda, numericality: {greater_than: 0}
end

webstore/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[ show edit update destroy ]

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to produto_url(@produto), notice: "Produto criado com sucesso." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to produto_url(@produto), notice: "Produto atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url, notice: "Produto excluído com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.require(:produto).permit(:nome, :preco_venda)
    end
end

webstore/app/helpers/produtos_helper.rb
module ProdutosHelper
end

webstore/app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true, :class => 'form-floating') do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger"><%= pluralize(compra.errors.count, compra.errors.count > 1 ? "erros impediram" : "erro impediu") %> que este produto fosse salvo:
				<ul>ls.compra.attribu
					<% produto.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
				</ul>
			</div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-floating mb-3">
  	    <%= form.text_field :nome, {class: "form-control"} %>
        <%= form.label :nome %>
      </div>
		</div>
    <div class="col-md-6">
      <div class="form-floating mb-3">
  	    <%= form.text_field :preco_venda, {class: "form-control"} %>
        <%= form.label :preco_venda %>
      </div>
		</div>
		<div class="actions pt-2 mb-2">
			<%= link_to 'Voltar', produtos_path, class: "btn btn-secondary text-white" %>
			<%= form.submit(:class => 'btn btn-success') %>
		</div>
	</div>
<% end %>

webstore/app/views/produtos/edit.html.erb
<h2>Editando Produto</h2>

<%= render 'form', produto: @produto %>

webstore/app/views/produtos/index.html.erb
<h2>Lista de Produtos</h2>
<p id="notice"><%= notice %></p>
<table id="datatable" class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Preço de venda</th>
      <th width>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td class="align-middle"><%= produto.try(:nome) %></td>
        <td class="align-middle"><%= number_to_currency(produto.try(:preco_venda), :precision => 2) %></td>
		
        <td>
			<%= link_to 'Exibir', produto, class: "btn btn-info text-white" %>
			<%= link_to 'Editar', edit_produto_path(produto), class: "btn btn-warning text-white" %>
			<%= link_to 'Excluir', produto, class: "btn btn-danger text-white", method: :delete, data: { confirm: 'Tem certeza?' } %>
		</td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Novo Produto', new_produto_path, class: "btn btn-primary text-white" %>

webstore/app/views/produtos/new.html.erb
<h2>Novo Produto</h2>

<%= render 'form', produto: @produto %>

webstore/app/views/produtos/show.html.erb
<h2>Exibindo Produto</h2>

<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<fieldset disabled>
	<div class="row">
		<div class="col-md-6">
			<div class="mb-3">
				<label class="form-label">Nome:</label>
				<input type="text" class="form-control" value="<%= @produto.nome %>">
			</div>
		</div>
		<div class="col-md-6">
			<div class="mb-3">
				<label class="form-label">Preço de venda:</label>
				<input type="text" class="form-control" value="<%= number_to_currency(@produto.preco_venda, :precision => 2) %>">
			</div>
		</div>
	</div>
</fieldset>

<%= link_to 'Voltar', produtos_path, class: "btn btn-secondary text-white" %>
<%= link_to 'Editar', edit_produto_path(@produto), class: "btn btn-warning text-white" %>