webstore/config/routes.rb
Rails.application.routes.draw do
  resources :clientes
  resources :produtos
  resources :fornecedores
  resources :acs do
    collection do
			get :autocomplete_fornecedor_nome
			get :autocomplete_produto_nome
    end
  end

  resources :compras do
    collection do
      put :gerar_parcelas
		end
  end
	
  root to: "welcome#index"
end

webstore/app/models/compra.rb
class Compra < ApplicationRecord
	attr_accessor :qtde_parcelas, :nro_dias_parcelas
	has_many :compra_itens, inverse_of: :compra, dependent: :destroy
	has_many :compras_a_pagar, inverse_of: :compra, dependent: :destroy

	belongs_to :fornecedor

	accepts_nested_attributes_for :compra_itens, allow_destroy: true
	accepts_nested_attributes_for :compras_a_pagar, allow_destroy: true
	
	validates :data, :fornecedor_id, :valor_total, presence: true
	
	validate :validar_totais

	def validar_totais
		self.gerar_valor_total
		valor_parcelas = self.calcular_total_parcelas

		if self.valor_total != valor_parcelas
			self.errors.add(:base, "A soma dos valores das parcelas (R$ #{valor_parcelas}) deve ser igual ao valor total da nota (R$ #{valor_total}).")
		end
		self.errors.blank?
	end

	def calcular_total_parcelas
		total_parcelas = 0.0
		self.compras_a_pagar.each do |parcela|
			total_parcelas += parcela.vlr_parcela
		end
		total_parcelas
	end

	def gerar_parcelas_compras
		parcelar_service = Utilitarios::ParcelarService.new(self.qtde_parcelas, self.nro_dias_parcelas, self.valor_total)
		parcelar_service.gerar
		parcelar_service.parcelas.each do |parcela|
			self.compras_a_pagar.build(
				nro_parcela: parcela.nro_parcela,
				data_vencto: parcela.data_vencto,
				vlr_parcela: parcela.vlr_parcela
			)
		end
	end

	def gerar_valor_total
		self.valor_total = 0.0
		
		self.compra_itens.each do |item|
			self.valor_total += item.vlr_total.to_s.to_d
		end
	end

	def get_competencia
		competencia = "#{self.data.year}#{self.data.month.to_s.rjust(2,'0')}".to_i
	end
end

webstore/app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :set_compra, only: %i[ show edit update destroy ]

  # GET /compras or /compras.json
  def index
    @compras = Compra.all
  end

  # GET /compras/1 or /compras/1.json
  def show
  end

  # GET /compras/new
  def new
    @compra = Compra.new
		@compra_itens = @compra.compra_itens.build
		#@compras_a_pagar = @compra.compras_a_pagar.build
  end

  # GET /compras/1/edit
  def edit
  end

  # POST /compras or /compras.json
  def create
    @compra = Compra.new(compra_params)

    respond_to do |format|
      if @compra.save
        format.html { redirect_to compra_url(@compra), notice: "Compra criada com sucesso." }
        format.json { render :show, status: :created, location: @compra }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compras/1 or /compras/1.json
  def update
    respond_to do |format|
      if @compra.update(compra_params)
        format.html { redirect_to compra_url(@compra), notice: "Compra atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @compra }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1 or /compras/1.json
  def destroy
    @compra.destroy

    respond_to do |format|
      format.html { redirect_to compras_url, notice: "Compra excluída com sucesso." }
      format.json { head :no_content }
    end
  end

		def get_compra
			compra = Compra.new
			compra = Compra.find(params[:id]) if params[:id].present?
			compra.attributes = compra_params
			compra.qtde_parcelas = params[:parcelas_a_gerar].to_s.to_i
			compra.nro_dias_parcelas = params[:intervalo_dias].to_s.to_i
			compra
		end

		def gerar_parcelas
			@compra = get_compra
			@compra.gerar_parcelas_compras
		end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra
      @compra = Compra.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def compra_params
      params.require(:compra).permit(
				:data, :fornecedor_id, :observacao, :valor_total, 
				compra_itens_attributes: [:id, :compra_id, :produto_id, :vlr_unitario, :vlr_total, :quantidade, :_destroy], 
				compras_a_pagar_attributes: [:id, :compra_id, :nro_parcela, :vlr_parcela, :data_vencto, :_destroy]
			)
    end

		def parametros
			params.permit!
		end
end

webstore/app/helpers/compras_helper.rb
module ComprasHelper
end

webstore/app/views/compras/_compra_a_pagar_fields.html.erb
<div class="nested-fields">
	<div class="row">
		<div class="col-md-3">
			<div class="form-floating field mb-3">
				<%= f.text_field :nro_parcela, {class: "form-control", min: "1", max: "12"} %>
				<%= f.label :nro_parcela %>
			</div>
		</div>
		<div class="col-md-4">
			<div class="form-floating field mb-3">
				<%= f.text_field :vlr_parcela, {class: "form-control", maxlength: 10} %>
				<%= f.label :vlr_parcela %>
			</div>
		</div>
		<div class="col-md-4">
			<div class="form-floating field mb-3">
				<%= f.date_field :data_vencto, {class: "form-control"} %>
				<%= f.label :data_vencto %>
			</div>
		</div>
		<div class="col-md-1 mb-4">
			<%= link_to_remove_association "Remover", f, class: "badge bg-danger mt-3" %>
		</div>
	</div>
</div>

webstore/app/views/compras/_compra_item_fields.html.erb
<div class="nested-fields">
	<div class="row">
		<div class="col-md-5">
			<div class="form-floating field mb-3" id="nome_<%= form_tag_id(f.object_name, :produto_id) %>">
				<%= autocomplete_field :produto, :nome,
					autocomplete_produto_nome_acs_path,
					:update_elements => { :id => "#"+ form_tag_id(f.object_name, :produto_id) },
					:class => "form-control",
					:id_element => "#"+ form_tag_id(f.object_name, :produto_id),
					:value => f.object.produto.try(:nome) %>
	      <%= f.label :produto %>
				<%= f.hidden_field :produto_id %>
			</div>
		</div>
		<div class="col-md-2">
			<div class="form-floating field mb-3">
				<%= f.number_field :quantidade, {class: "form-control", min: "0.00", max: "999999.00", step: "0.5"} %>
				<%= f.label :quantidade %>
			</div>
		</div>
		<div class="col-md-2">
			<div class="form-floating field mb-3">
				<%= f.text_field :vlr_unitario, {class: "form-control", maxlength: 10} %>
				<%= f.label :vlr_unitario %>
			</div>
		</div>
		<div class="col-md-2">
			<div class="form-floating field mb-3">
				<%= f.text_field :vlr_total, {class: "form-control", maxlength: 10} %>
				<%= f.label :vlr_total %>
			</div>
		</div>
		<div class="col-md-1 mb-4">
			<%= link_to_remove_association "- Remover", f, class: "badge bg-danger mt-3" %>
		</div>
	</div>
</div>

webstore/app/views/compras/_compras_a_pagar_parcelas.html.erb
<%= form.fields_for :compras_a_pagar do |compra_a_pagar| %>
	<%= render 'compra_a_pagar_fields', f: compra_a_pagar %>
<% end %>

<% if @compra.id %>
	<div class="links">
		<%= link_to_add_association "+ Adicionar parcela", form, :compras_a_pagar, class: "badge bg-primary mb-2" %>
	</div>
<% end %>

webstore/app/views/compras/_form.html.erb
<%= form_with(model: compra, local: true, :class => 'form-floating') do |form| %>
  <% if compra.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger"><%= pluralize(compra.errors.count, compra.errors.count > 1 ? "erros impediram" : "erro impediu") %> que esta compra fosse salva:
				<ul>
					<% compra.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
				</ul>
			</div>
    </div>  
  <% end %>
	<div class="row">
	  <div class="col-md-6">
	    <div class="form-floating mb-3">
	      <%= form.date_field :data, {class: "form-control"} %>
	      <%= form.label :data %>
	    </div>
	  </div>
	  <div class="col-md-6">
	    <div class="form-floating mb-3">
	    <%= form.text_field :valor_total, {class: "form-control", id: "valor_total"} %>
	    <%= form.label :valor_total %>
	    </div>
	  </div>
	</div>
	<div class="row">
	  <div class="col-md-12 mb-3">
	    <div class="form-floating mb-3" id="nome_<%= form_tag_id(form.object_name, :fornecedor_id) %>">
				<%= autocomplete_field :fornecedor, :nome,
					autocomplete_fornecedor_nome_acs_path,
					:update_elements => { :id => "#"+ form_tag_id(form.object_name, :fornecedor_id) },
					:class => "form-control",
					:id_element => "#"+ form_tag_id(form.object_name, :fornecedor_id),
					:value => form.object.fornecedor.try(:nome) %>
	      <%= form.label :fornecedor %>
				<%= form.hidden_field :fornecedor_id %>
	    </div>
	  </div>
	</div>
	<div class="row">
	  <div class="col-md-12">
	    <div class="form-floating mb-3">
	      <%= form.text_area :observacao, {class: "form-control"} %>
	      <%= form.label :observacao %>
	    </div>
	  </div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<ul class="nav nav-tabs" id="myTab" role="tablist">
				<li class="nav-item" role="presentation">
					<button class="nav-link active" id="produtos-tab" data-bs-toggle="tab" data-bs-target="#produtos-tab-pane" type="button" role="tab" aria-controls="produtos-tab-pane" aria-selected="true">Produtos</button>
				</li>
				<li class="nav-item" role="presentation">
					<button class="nav-link" id="pagamento-tab" data-bs-toggle="tab" data-bs-target="#pagamento-tab-pane" type="button" role="tab" aria-controls="pagamento-tab-pane" aria-selected="false">Pagamento</button>
				</li>
			</ul>
			<div class="tab-content" id="myTabContent">
				<div class="tab-pane fade show active" id="produtos-tab-pane" role="tabpanel" aria-labelledby="produtos-tab" tabindex="0">
					<div class="row">
						<h5 class="mt-3 mb-3">Lançamento de produtos</h5>
						<div id="compra_itens">
							<%= form.fields_for :compra_itens do |compra_item| %>
								<%= render 'compra_item_fields', f: compra_item %>
							<% end %>
							<div class="links">
								<%= link_to_add_association "+ Adicionar produto", form, :compra_itens, class: "badge bg-primary mb-2" %>
							</div>
						</div>
					</div>
				</div>
				<div class="tab-pane fade" id="pagamento-tab-pane" role="tabpanel" aria-labelledby="pagamento-tab" tabindex="0">
					<div class="row">
						<h5 class="mt-3 mb-3">Forma de pagamento</h5>
						<% if @compra.new_record? %>
						<div class="col-md-2">
							<div class="form-floating mb-3">
							<%= number_field_tag 'parcelas_a_gerar', 3, {class: "form-control", min: "1", max: "12"} %>
							<%= form.label :parcelas_a_gerar %>
							</div>
						</div>
						<div class="col-md-2">
							<div class="form-floating mb-3">
								<%= number_field_tag 'intervalo_dias', 30, {class: "form-control", min: "1", max: "45"} %>
	      				<%= form.label :intervalo_dias %>
							</div>
						</div>
						<div class="col-md-2 mt-3">
								<%= link_to "Gerar parcela(s)", '#', id: 'gerar_parcela', class: "badge bg-primary" %>
						</div>
						<% end %>
						<hr>
						<div id="compras_a_pagar">
							<%= render 'compras_a_pagar_parcelas', form: form %>
						</div>
					</div>	
				</div>
			</div>
		</div>
	</div>
	<div class="row">
	  <div class="actions pt-2 mb-2">
			<hr>
			<%= link_to 'Voltar', compras_path, class: "btn btn-secondary text-white" %>
	    <%= form.submit(:class => 'btn btn-success') %>
	  </div>
	</div>
<% end %>
<script>
  function gerar_parcelas() {
    $.ajax({
      url: "<%= gerar_parcelas_compras_path %>",
      data: $("form").serialize()+"&id=<%= @compra.id %>",
      async: false,
      type: 'put'
    });
  }

  $("#gerar_parcela").on('click', function(event) {
    event.preventDefault();
    gerar_parcelas();
  });

	//ajuste de previsão casas decimais
	const round = (num, places) => {
		if (!("" + num).includes("e")) {
			return +(Math.round(num + "e+" + places)  + "e-" + places);
		} else {
			let arr = ("" + num).split("e");
			let sig = ""
			if (+arr[1] + places > 0) {
				sig = "+";
			}

			if (!true != !false) {
				console.log(!true);
			}

			return +(Math.round(+arr[0] + "e" + sig + (+arr[1] + places)) + "e-" + places);
		}
	}

	function calcula_vlr_unitario() {
    var quantidade = document.getElementById('quantidade').value;
    var vlr_total = document.getElementById('vlr_total').value;
    var calcula_vlr_unitario = document.getElementById('vlr_unitario').value = round(vlr_total, 10) / round(quantidade, 1);
    var calcula_vlr_total = document.getElementById('valor_total').value = round(vlr_total, 10);
	}
</script>

webstore/app/views/compras/edit.html.erb
<h2>Editando Compra</h2>

<%= render 'form', compra: @compra %>

webstore/app/views/compras/gerar_parcelas.js.erb
<%
  @form_compra = nil
  form_for(@compra, :validate => true) { |form| @form_compra = form }
%>
$("#compras_a_pagar").html("<%= escape_javascript( render 'compras_a_pagar_parcelas', :form => @form_compra ) %>") ;

webstore/app/views/compras/index.html.erb
<h2>Lista de Compras</h2>
<p id="notice"><%= notice %></p>
<table id="datatable" class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Data</th>
      <th>Fornecedor</th>
      <th>Valor total</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @compras.each do |compra| %>
      <tr>
        <td class="align-middle"><%= compra.try(:data) %></td>
        <td class="align-middle"><%= compra.fornecedor.try(:nome) %></td>
        <td class="align-middle"><%= number_to_currency(compra.try(:valor_total), :precision => 2) %></td>
        <td>
			<%= link_to 'Exibir', compra, class: "btn btn-info text-white" %>
			<%= link_to 'Editar', edit_compra_path(compra), class: "btn btn-warning text-white" %>
			<%= link_to 'Excluir', compra, class: "btn btn-danger text-white", method: :delete, data: { confirm: 'Tem certeza que deseja excluir esta compra? Este processo é irreversível.' } %>
		</td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Nova Compra', new_compra_path, class: "btn btn-primary text-white" %>

webstore/app/views/compras/new.html.erb
<h2>Nova Compra</h2>

<%= render 'form', compra: @compra %>

webstore/app/views/compras/show.html.erb
<h2>Exibindo Compra</h2>

<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<fieldset disabled>
	<div class="row">
		<div class="col-md-2">
			<div class="mb-3">
				<label class="form-label">Data:</label>
				<input type="text" class="form-control" value="<%= @compra.try(:data) %>">
			</div>
		</div>
		<div class="col-md-8">
			<div class="mb-3">
				<label class="form-label">Fornecedor:</label>
				<input type="text" class="form-control" value="<%= @compra.fornecedor.try(:nome) %>">
			</div>
		</div>
		<div class="col-md-2">
			<div class="mb-3">
				<label class="form-label">Valor total:</label>
				<input type="text" class="form-control" value="<%= number_to_currency(@compra.try(:valor_total), :precision => 2) %>">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="mb-3">
				<label class="form-label">Observações:</label>
				<input type="text" class="form-control" value="<%= @compra.try(:observacao) %>">
			</div>
		</div>
	</div>
</fieldset>
<hr>
<div class="row">
	<div class="col-md-12">
		<ul class="nav nav-tabs" id="myTab" role="tablist">
			<li class="nav-item" role="presentation">
				<button class="nav-link active" id="produtos-tab" data-bs-toggle="tab" data-bs-target="#produtos-tab-pane" type="button" role="tab" aria-controls="produtos-tab-pane" aria-selected="true">Produtos</button>
			</li>
			<li class="nav-item" role="presentation">
				<button class="nav-link" id="pagamento-tab" data-bs-toggle="tab" data-bs-target="#pagamento-tab-pane" type="button" role="tab" aria-controls="pagamento-tab-pane" aria-selected="false">Pagamento</button>
			</li>
		</ul>
		<div class="tab-content" id="myTabContent">
			<div class="tab-pane fade show active" id="produtos-tab-pane" role="tabpanel" aria-labelledby="produtos-tab" tabindex="0">
				<div class="row">
					<h5 class="mt-3 mb-3">Produtos da compra</h5>
					<fieldset disabled>
						<div class="row">
							<div class="col-md-6">
								<label class="form-label">Produto</label>
							</div>
							<div class="col-md-2">
								<label class="form-label">Quantidade</label>
							</div>
							<div class="col-md-2">
								<label class="form-label">Valor unitário</label>
							</div>
							<div class="col-md-2">
								<label class="form-label">Valor total</label>
							</div>
						</div>
						<% @compra.compra_itens.each do |ci| %>
						<div class="row">
							<div class="col-md-6">
								<div class="mb-3">
									<input type="text" class="form-control" value="<%= ci.produto.try(:nome) %>">
								</div>
							</div>
							<div class="col-md-2">
								<div class="mb-3">
									<input type="text" class="form-control" value="<%= ci.try(:quantidade) %>">
								</div>
							</div>
							<div class="col-md-2">
								<div class="mb-3">
									<input type="text" class="form-control" value="<%= number_to_currency(ci.try(:vlr_unitario), :precision => 2) %>">
								</div>
							</div>
							<div class="col-md-2">
								<div class="mb-3">
									<input type="text" class="form-control" value="<%= number_to_currency(ci.try(:vlr_total), :precision => 2) %>">
								</div>
							</div>
						</div>
						<% end %>
					</fieldset>
				</div>
			</div>			
			<div class="tab-pane fade" id="pagamento-tab-pane" role="tabpanel" aria-labelledby="pagamento-tab" tabindex="0">
				<div class="row">
					<h5 class="mt-3 mb-3">Forma de pagamento escolhida</h5>
					<fieldset disabled>
						<div class="row">
							<div class="col-md-4">
								<label class="form-label">Nro Parcela</label>
							</div>
							<div class="col-md-4">
								<label class="form-label">Valor parcela</label>
							</div>
							<div class="col-md-4">
								<label class="form-label">Vencimento</label>
							</div>
						</div>
						<% @compra.compras_a_pagar.each do |cp| %>
						<div class="row">
							<div class="col-md-4">
								<div class="mb-3">
									<input type="text" class="form-control" value="<%= cp.try(:nro_parcela) %>">
								</div>
							</div>
							<div class="col-md-4">
								<div class="mb-3">
									<input type="text" class="form-control" value="<%= number_to_currency(cp.try(:vlr_parcela ), :precision => 2) %>">
								</div>
							</div>
							<div class="col-md-4">
								<div class="mb-3">
									<input type="text" class="form-control" value="<%= cp.try(:data_vencto) %>">
								</div>
							</div>
						</div>
						<% end %>
					</fieldset>
				</div>	
			</div>
		</div>
	</div>
</div>
<hr>

<%= link_to 'Voltar', compras_path, class: "btn btn-secondary text-white" %>
<%= link_to 'Editar', edit_compra_path(@compra), class: "btn btn-warning text-white" %>