webstore/config/routes.rb
Rails.application.routes.draw do
  resources :clientes
  resources :produtos
  resources :fornecedores
  resources :acs do
    collection do
			get :autocomplete_fornecedor_nome
			get :autocomplete_produto_nome
    end
  end

  resources :compras do
    collection do
      put :gerar_parcelas
		end
  end
	
  root to: "welcome#index"
end

webstore/app/models/cliente.rb
class Cliente < ApplicationRecord
  validates :nome, :cpf_cnpj, presence: true
  validates :cpf_cnpj, uniqueness: true
end

webstore/app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente criado com sucesso." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente excluído com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nome, :cpf_cnpj)
    end
end

webstore/app/helpers/clientes_helper.rb
module ClientesHelper
end

webstore/app/views/clientes/_form.html.erb
<%= form_with(model: cliente, local: true, :class => 'form-floating') do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger"><%= pluralize(compra.errors.count, compra.errors.count > 1 ? "erros impediram" : "erro impediu") %> que esta compra fosse salva:
				<ul>
					<% cliente.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
				</ul>
			</div>
    </div>
  <% end %>

  <div class="row">
    <div class="col">
      <div class="form-floating mb-3">
  	    <%= form.text_field :nome, {class: "form-control"} %>
        <%= form.label :nome %>
      </div>
	</div>
    <div class="col">
      <div class="form-floating mb-3">
  	    <%= form.text_field :cpf_cnpj, {class: "form-control"} %>
        <%= form.label :cpf_cnpj %>
      </div>
	</div>
    <div class="actions pt-2 mb-2">
			<%= link_to 'Voltar', clientes_path, class: "btn btn-secondary text-white" %>
      <%= form.submit(:class => 'btn btn-success') %>
    </div>
  </div>
<% end %>

webstore/app/views/clientes/edit.html.erb
<h2>Editando Cliente</h2>

<%= render 'form', cliente: @cliente %>

webstore/app/views/clientes/index.html.erb
<h2>Lista de Clientes</h2>
<p id="notice"><%= notice %></p>
<table id="datatable" class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>CPF/CPNJ</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td class="align-middle"><%= cliente.try(:nome) %></td>
        <td class="align-middle"><%= cliente.try(:cpf_cnpj) %></td>
		
        <td>
			<%= link_to 'Exibir', cliente, class: "btn btn-info text-white" %>
			<%= link_to 'Editar', edit_cliente_path(cliente), class: "btn btn-warning text-white" %>
			<%= link_to 'Excluir', cliente, class: "btn btn-danger text-white", method: :delete, data: { confirm: 'Tem certeza?' } %>
		</td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Novo Cliente', new_cliente_path, class: "btn btn-primary text-white" %>

webstore/app/views/clientes/new.html.erb
<h2>Novo Cliente</h2>

<%= render 'form', cliente: @cliente %>

webstore/app/views/clientes/show.html.erb
<h2>Exibindo Cliente</h2>

<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>


<fieldset disabled>
<div class="row">
	<div class="col-md-6">
  	<div class="mb-3">
  	  <label class="form-label">Nome:</label>
  	  <input type="text" class="form-control" value="<%= @cliente.nome %>">
  	</div>
	</div>
	<div class="col-md-6">
		<div class="mb-3">
			<label class="form-label">CPF/CNPJ:</label>
			<input type="text" class="form-control" value="<%= @cliente.cpf_cnpj %>">
		</div>
	</div>
</div>
</fieldset>
<%= link_to 'Voltar', clientes_path, class: "btn btn-secondary text-white" %>
<%= link_to 'Editar', edit_cliente_path(@cliente), class: "btn btn-warning text-white" %>